/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import com.eomcs.pms.handler.MemberHandler;
import com.eomcs.pms.handler.ProjectHandler;
import com.eomcs.pms.handler.TaskHandler;
import com.eomcs.pms.util.Prompt;

public class App {

  public static void main(String[] args) {
    MemberHandler memberHandler = new MemberHandler();
    ProjectHandler projectHandler = new ProjectHandler();
    TaskHandler taskHandler = new TaskHandler();
    Prompt prompt = new Prompt();

    loop:
    while (true) {

      String input = prompt.promptString("명령 > ");

      switch (input) {
        case "/member/add" :
          memberHandler.inputMembers();
          break;
        case "/member/list" :
          System.out.println("[회원 목록]");
          memberHandler.printMembers();
          break;
        case "/project/add" :
          projectHandler.inputProjects();
          break;
        case "/project/list" :
          System.out.println("[프로젝트 목록]");
          projectHandler.printProjects();
          break;
        case "/task/add" :
          taskHandler.inputTasks();
          break;
        case "/task/list" :
          System.out.println("[작업 목록]");
          taskHandler.printTasks();
          break;
        case "exit" :
        case "quit" :
          System.out.println("입력을 종료합니다.");
          break loop;
        default :
          System.out.println("실행할 수 없는 명령입니다.");
        }
    }
    prompt.close();
  }
}
