/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import java.sql.Date;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {

      System.out.println("[회원]");

      Scanner in = new Scanner(System.in);
      Date date = new Date(System.currentTimeMillis());


        System.out.print("번호? ");
        String no = in.nextLine();

        System.out.print("이름? ");
        String name = in.nextLine();

        System.out.print("이메일? ");
        String email = in.nextLine();

        System.out.print("암호? ");
        String password = in.nextLine();

        System.out.print("사진? ");
        String picture = in.nextLine();

        System.out.print("전화? ");
        String tel = in.nextLine();

        in.close();

        System.out.println("--------------------");
        System.out.println("번호 : " + no);
        System.out.println("이름 : " + name);
        System.out.println("이메일 : " + email);
        System.out.printf("암호 : %s\n ", password);
        System.out.printf("사진 : %s\n ", picture);
        System.out.printf("전화 : %s\n", tel);
        System.out.printf("가입일 : %s\n ", date);
    }
}
