/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

//1) 낱개의 변수를 사용하여 여러 회원 정보 처리하기
//2) 조건문을 사용하여 입출력 제어하기
//- 필요한 만큼만 입력 받고 출력하고 싶다.

import java.sql.Date;
import java.util.Scanner;

public class App {
  static Scanner in = new Scanner(System.in);

  static final int LENGTH = 5;

  static int[] no = new int[LENGTH];
  static String[] name = new String[LENGTH];
  static String[] email = new String[LENGTH];
  static String[] password = new String[LENGTH];
  static String[] picture = new String[LENGTH];
  static String[] tel = new String[LENGTH];
  static Date registeredDate = new Date(System.currentTimeMillis());

  static int size = 0;

  static void inputMembers() {
      for (int i = 0; i < 5; i++) {
      System.out.println("[회원]" );

        System.out.print("번호? ");
        no[i] = Integer.parseInt(in.nextLine());

        System.out.print("이름? ");
        name[i] = in.nextLine();

        System.out.print("이메일? ");
        email[i] = in.nextLine();

        System.out.print("암호? ");
        password[i] = in.nextLine();

        System.out.print("사진? ");
        picture[i] = in.nextLine();

        System.out.print("전화? ");
        tel[i] = in.nextLine();

        size++;

        System.out.print("계속 입력하시겠습니까?(Y/n)");
        String answer = in.nextLine();
        if (!answer.equalsIgnoreCase("y")) {
          break;
        }
      }
  }
    static void printMembers() {
      for (int i = 0; i < size; i++) {
        System.out.printf("%d, %s, %s, %s, %s, %s, %s\n", no[i], name[i], email[i], password[i],
            picture[i], tel[i], registeredDate);
   }
    }
    public static void main(String[] args) {
      inputMembers();
      System.out.println("--------------------");
      in.close();
      printMembers();
    }
}
